import { Outfit } from "next/font/google"; // Correct import for Google font
import localFont from "next/font/local"; // Import local font correctly
import "./globals.css";

// Load Google Outfit font
const outfit = Outfit({
  subsets: ['latin'],
  weight: ["400", "500", "600", "700"],
});

// Load local GeistMono font
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}